"""Ensure role column exists

Revision ID: 368289f42cef
Revises: 
Create Date: 2025-09-12 16:50:35.864444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368289f42cef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('timetables')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetables',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('department', sa.VARCHAR(length=100), nullable=False),
    sa.Column('semester', sa.VARCHAR(length=50), nullable=False),
    sa.Column('data', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=200), nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
